---
# INFO: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml for full list of rules
MD013:
  line_length: 320
MD007:
  indent: 4
MD033: false
MD010: false
MD045: false
MD041: false
MD024: false
MD046: false

