repos:
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
      - id: alejandra-system
  - repo: https://github.com/astro/deadnix
    rev: v1.2.1
    hooks:
      - id: deadnix
        args: [--edit] # Uncomment to automatically modify files
        stages: [commit]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf
      - id: remove-tabs

  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.3
    hooks:
      - id: fix-smartquotes
      - id: fix-ligatures

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: statix warnings
        name: statix warnings
        entry: statix check .
        pass_filenames: false
        language: system
        always_run: true
        types: [nix]
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.23.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
