{config, ...}: let
  nameservers =
    if config.services.adguardhome.enable
    then ["100.100.100.100" "127.0.0.1"]
    else ["127.0.0.1"];
in {
  environment.etc."resolv.conf".text = ''
    # Generated by NixOS Configuration (see profiles/networking/dns.nix)
    search zapus-perch.ts.net
    nameserver 127.0.0.1
    options edns0 trust-ad
  '';
  # Networking basics (hostname excluded)
  networking = {
    inherit nameservers;
    networkmanager.appendNameservers = nameservers;
    resolvconf = {
      # I disabled resolvconf in favour of setting it myself as this removes the "magic" of who is first. If someone overwrites it then reslovconf overwrites it again you don't know what has happened, this way you do, as the environment.etc is always first so if anything overwrites it it will be obvious.
      enable = false; # Written manually above
      # # This config (with tailsacle) will result in a /etc/resolv.conf like this:
      # search zapus-perch.ts.net
      # nameserver 127.0.0.1
      # options edns0 trust-ad
      #
      # useLocalResolver = true;
      # dnsExtensionMechanism = true;
    };
  };

  services.dnsproxy = {
    enable = !config.services.adguardhome.enable; # Turn on the dnsproxy service if its not running adguardhome directly
    settings = {
      cache = true; # Enables caching of DNS responses.
      cache-min-ttl = 1; # Sets the minimum time-to-live for cached entries to 1 second.
      cache-max-ttl = 300; # Sets the maximum time-to-live for cached entries to 5 minutes.
      cache-optimistic = true; # Responds from cache even when the entries are expired but then refreshes them.
      cache-size = 4194304; # Sets the cache size to 4 MiB.
      fallback = ["9.9.9.9"]; # Fallback DNS server if upstreams fail.
      listen-addrs = ["127.0.0.1"]; # Listens on your local computer (127.0.0.1).
      listen-ports = [53]; # Default DNS port (port 53). This will handle DNS requests.
      upstream = [
        # Tailscale
        "100.91.21.102" # OpnSense
        "100.124.150.44" # Orth
        "[/zapus-perch.ts.net/]100.100.100.100"
      ];
      upstream-mode = "parallel";
      verbose = true;
    };
  };
}
