name: Clean and Update
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 19 * * 6' # every Saturday at 19:00 UTC
jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    env:
      # Done as a separte action.
      SKIP: "ggshield,deadnix,statix"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-env -i alejandra -f '<nixpkgs>'
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  deadnix:
    name: Look for dead code paths
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: deadnix
      - uses: astro/deadnix-action@main

  statix:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v12
        with:
          name: statix
      - uses: jocelynthode/statix-action@master

  lockfile:
    name: Update flake.lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated

  slack-msg:
    name: Post to a Slack channel
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'C06RDK6G4M7'
          slack-message: "Ran NixOs Clean and Update action, check for PRs."
          webhookUrl: ${{ secrets.SLACK_BOT_TOKEN }}
