name: Clean and Update
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 19 * * 6' # every Saturday at 19:00 UTC
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix with KVM enabled
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          enable_kvm: true
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Check nix.conf
        run: cat /etc/nix/nix.conf
      - run: sudo apt -y install qemu-user-static
      - name: Test binfmt availability
        run: |
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64
          /usr/bin/qemu-aarch64-static --version
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:gh
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: "http://atticd:8080"
          cache: atro
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
      - name: Run build
        run: |
          nix flake update
          nix build .#nixosConfigurations.giant.config.system.build.toplevel -L
