---
name: Test
on:
  workflow_call:
    inputs:
      bump-flake-lock:
        description: 'Bump flake.lock'
        required: false
        default: false
        type: boolean
  pull_request:
    branches: ["main"]
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix with KVM enabled
        uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          enable_kvm: true
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Prepare host for ARM64 emulation
        run: |
          sudo apt update -y
          sudo apt -y install qemu-user-static
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64
          /usr/bin/qemu-aarch64-static --version
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Bump flake.lock
        if: ${{ inputs.bump-flake-lock}} == true
        run: nix flake update
      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
