name: Test
on:
  workflow_call:
  pull_request:
    branches: ["main"]
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:gh
      - name: Install Nix with KVM enabled
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          enable_kvm: true
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Prepare host for ARM64 emulation
        run: |
          sudo apt update -y
          sudo apt -y install qemu-user-static
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64
          /usr/bin/qemu-aarch64-static --version
      - name: Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: "http://atticd:8080"
          cache: atro
          token: ${{ secrets.ATTIC_TOKEN }}
          skip-push: true
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
