name: Build and Release SD Images
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    name: Create and Upload Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build Images
        run: |
          nix build .#sdImage-opi1 --verbose
          nix build .#sdImage-opi2 --verbose
          nix build .#sdImage-opi3 --verbose
          nix build .#sdImage-opi4 --verbose
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          gh release create --draft $TAG_NAME --title $TAG_NAME
      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          FILES=./result/sd-image/**
          for file in $FILES; do
            if [ -f "$file" ]; then
              echo "Uploading $file"
              gh release upload $TAG_NAME "$file" --clobber
            fi
          done
