name: Test
on:
  pull_request:
    branches: ["main"]
  push:
    branches:
      - "main"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      # Done as a separte action.
      SKIP: "ggshield"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          enable_kvm: true
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - run: nix-env -i alejandra deadnix statix -f '<nixpkgs>'
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          enable_kvm: true
      - run: nix flake check
